config/routes.rb
Rails.application.routes.draw do
  resources :classrooms

  resources :courses

  resources :students

  root 'application#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
end

app/models/course.rb
class Course < ActiveRecord::Base
  VALID_NAME_REGEX = /[a-z]/i
  validates :name, :presence => true, :length => {:in => 3..45}, format: { with: VALID_NAME_REGEX }

  VALID_DESCRIPTION_REGEX = /\w/i
  validates :description, :presence => true, :length => {:in => 3..45}, format: { with: VALID_DESCRIPTION_REGEX }

  VALID_STATUS_REGEX = /\d/i
  validates :status, :presence => true, format: { with: VALID_STATUS_REGEX }
end

app/models/student.rb
class Student < ActiveRecord::Base
  VALID_NAME_REGEX = /[a-z]/i
  validates :name, :presence => true, :length => {:in => 3..45}, format: { with: VALID_NAME_REGEX }

  VALID_REGISTER_NUMBER_REGEX = /\w/i
  validates :register_number, :presence => true, :length => {:in => 3..45}, format: { with: VALID_REGISTER_NUMBER_REGEX }

  VALID_STATUS_REGEX = /\d/i
  validates :status, :presence => true, format: { with: VALID_STATUS_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout "application"

  def index
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  # GET /classrooms
  # GET /classrooms.json
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
    @students = Student.all
    @courses = Course.all
  end

  # GET /classrooms/1/edit
  def edit
    set_dependencies
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to @classroom, notice: 'Classroom was successfully created.' }
        format.json { render action: 'show', status: :created, location: @classroom }
      else
        format.html { render action: 'new' }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1
  # PATCH/PUT /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to @classroom, notice: 'Classroom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_params
      params.require(:classroom).permit(:student_id, :course_id, :entry_at)
    end

    def set_dependencies
      @students = Student.all
      @courses = Course.all
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    Classroom.where(['course_id = ?', @course.id]).destroy_all
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :status)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    Classroom.where(['student_id = ?', @student.id]).destroy_all
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :register_number, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/application/index.html.erb
<section class="index-container"
  ng-controller="IndexApplicationController as index">
  <a class="students col-md-6 col-sm-6 col-xs-12" href="/students">
    <span>Students</span>
  </a>
  <a class="courses col-md-6 col-sm-6 col-xs-12" href="/courses">
    <span>Courses</span>
  </a>
  <a class="classrooms col-md-12 col-sm-12 col-xs-12" href="/classrooms">
    <span>Classrooms</span>
  </a>
</div>

app/views/classrooms/_form.html.erb
<%= simple_form_for @classroom, :html => {:role => 'form', :"data-toggle" => 'validator'} do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= label_tag(:student_id, "Student") %>
    <%= f.select(:student_id,
      options_from_collection_for_select(@students, 'id', 'name', :selected => @classroom.student_id),
      { :include_blank => true },
      { :class => 'form-control', :required => 'required' },
    ) %>
    <span class="help-block with-errors"></span>
  </div>

  <div class="form-group">
    <%= label_tag(:course_id, "Course") %>
    <%= f.select(:course_id,
      options_from_collection_for_select(@courses, 'id', 'name', :selected => @classroom.course_id),
      { :include_blank => true },
      { :class => 'form-control', :required => 'required' }
    ) %>
    <span class="help-block with-errors"></span>
  </div>

  <div class="form-group">
    <%= label_tag(:entry_at, "Entry At") %>
    <%= f.text_field :entry_at,
      class: ['form-control'],
      id: 'entry_at',
      maxlength: '45',
      placeholder: 'YYYY-mm-dd HH:ii:ss',
      pattern: "^\d{4}\-\d{2}\-\d{2}\s\d{2}\:\d{2}\:\d{2}$",
      required: 'required'
    %>
    <span class="help-block with-errors"></span>
  </div>

  <%= f.button :submit, class: ['btn-primary', 'pull-right'] %>
<% end %>

app/views/classrooms/edit.html.erb
<section class="classrooms-edit-container">
  <div class="jumbotron">
    <div class="container">
      <h1>Editing classroom</h1>
    </div>
  </div>

  <div class="container">
    <%= render 'form' %>
    <%= link_to 'Back', classrooms_path, class: ['btn', 'btn-default', 'pull-left'] %>
    <%= link_to 'Show', @classroom, class: ['btn', 'btn-default', 'pull-left'] %>
  </div>
</section>

app/views/classrooms/index.html.erb
<section class="classrooms-index-container"
  ng-controller="ClassroomsIndexController as classroomsIndexController">
  <div class="jumbotron">
    <div class="container">
      <h1>Listing classrooms</h1>
    </div>
  </div>

  <div class="container">
    <table class="table table-responsive">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Regiter Number</th>
          <th>Course</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @classrooms.each do |classroom| %>
          <tr>
            <td><%= classroom.id %></td>
            <td><%= classroom.student.name %></td>
            <td><%= classroom.student.register_number %></td>
            <td><%= classroom.course.name %></td>
            <td><%= classroom.course.description %></td>
            <td><%= link_to 'Show', classroom %></td>
            <td><%= link_to 'Edit', edit_classroom_path(classroom) %></td>
            <td><%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Back', root_path, class: ['btn', 'btn-default', 'pull-left'] %>
    <%= content_tag(:a, 'New Classroom',
      class: ['btn', 'btn-primary', 'pull-right'],
      type: 'text',
      href: new_classroom_path
    ) %>
  </div>
</section>

app/views/classrooms/new.html.erb
<section class="classrooms-new-container">
  <div class="jumbotron">
    <div class="container">
      <h1>New classrooms</h1>
    </div>
  </div>

  <div class="container">
    <%= render 'form' %>
    <%= link_to 'Back', classrooms_path, class: ['btn', 'btn-default', 'pull-left'] %>
  </div>
</section>

app/views/classrooms/show.html.erb
<section class="classrooms-show-container">
  <div class="jumbotron">
    <div class="container">
      <h1>Classroom</h1>
    </div>
  </div>

  <div class="container">
    <% if notice %>
      <div class="alert alert-success" role="alert">
        <span class="sr-only">Success:</span>
        <%= notice %>
      </div>
    <% end %>

    <h4>Classroom</h4>
    <table class="table table-responsive">
      <tbody>
        <tr>
          <td class="col-md-3 col-sm-3 col-xs-4"><b>#</b></td>
          <td><%= @classroom.id %></td>
        </tr>
        <tr>
          <td><b>Entry At</b></td>
          <td><%= @classroom.entry_at %></td>
        </tr>
      </tbody>
    </table>

    <h4>Student</h4>
    <table class="table table-responsive">
      <tbody>
        <tr>
          <td class="col-md-3 col-sm-3 col-xs-4"><b>#</b></td>
          <td><%= @classroom.student.id %></td>
        </tr>
        <tr>
          <td><b>Name</b></td>
          <td><%= @classroom.student.name %></td>
        </tr>
        <tr>
          <td><b>Register Number</b></td>
          <td><%= @classroom.student.register_number %></td>
        </tr>
        <tr>
          <td><b>Status</b></td>
          <td><%= @classroom.student.status %></td>
        </tr>
      </tbody>
    </table>

    <h4>Course</h4>
    <table class="table table-responsive">
      <tbody>
        <tr>
          <td class="col-md-3 col-sm-3 col-xs-4"><b>#</b></td>
          <td><%= @classroom.course.id %></td>
        </tr>
        <tr>
          <td><b>Name</b></td>
          <td><%= @classroom.course.name %></td>
        </tr>
        <tr>
          <td><b>Description</b></td>
          <td><%= @classroom.course.description %></td>
        </tr>
        <tr>
          <td><b>Status</b></td>
          <td><%= @classroom.course.status %></td>
        </tr>
        <tr>
        </tr>
      </tbody>
    </table>

    <%= link_to 'Back', classrooms_path, class: ['btn', 'btn-default', 'pull-left'] %>
    <%= link_to 'Home', root_path(), class: ['btn', 'btn-primary', 'pull-right'] %>
    <%= link_to 'Edit', edit_classroom_path(@classroom), class: ['btn', 'btn-default', 'pull-right'] %>
  </div>
</section>

app/views/courses/_form.html.erb
<%= simple_form_for @course, :html => {:role => 'form', :"data-toggle" => 'validator'} do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= label_tag(:name, "Name") %>
    <%= f.text_field :name,
      class: ['form-control'],
      id: 'name',
      :required => 'required',
      pattern: "^[a-zA-Z\u00C0-\u00FF\s]+$",
      maxlength: '45',
      autofocus: 'autofocus'
    %>
    <span class="help-block with-errors"></span>
  </div>
  <div class="form-group">
    <%= label_tag(:description, "Description") %>
    <%= f.text_field :description,
      class: ['form-control'],
      id: 'description',
      pattern: "^[a-zA-Z\u00C0-\u00FF\s]+$",
      :required => 'required',
      maxlength: '45'
    %>
    <span class="help-block with-errors"></span>
  </div>
  <div class="form-group">
    <%= label_tag(:status, "Status") %>
    <%= f.number_field :status,
      class: ['form-control'],
      id: 'status',
      pattern: "^[0-9]+$",
      :required => 'required',
      min: '0'
    %>
    <span class="help-block with-errors"></span>
  </div>
  <%= f.button :submit, class: ['btn-primary', 'pull-right'] %>
<% end %>

app/views/courses/edit.html.erb
<section class="courses-edit-container">
  <div class="jumbotron">
    <div class="container">
      <h1>Editing course</h1>
    </div>
  </div>

  <div class="container">
    <%= render 'form' %>
    <%= link_to 'Back', courses_path, class: ['btn', 'btn-default', 'pull-left'] %>
    <%= link_to 'Show', @course, class: ['btn', 'btn-default', 'pull-left'] %>
  </div>
</section>

app/views/courses/index.html.erb
<section class="courses-index-container"
  ng-controller="CoursesIndexController as coursesIndexController">
  <div class="jumbotron">
    <div class="container">
      <h1>Listing Courses</h1>
    </div>
  </div>

  <div class="container">
    <table class="table table-responsive">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Description</th>
          <th>Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @courses.each do |course| %>
          <tr>
            <td><%= course.id %></td>
            <td><%= course.name %></td>
            <td><%= course.description %></td>
            <td><%= course.status %></td>
            <td><%= link_to 'Show', course %></td>
            <td><%= link_to 'Edit', edit_course_path(course) %></td>
            <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Back', root_path, class: ['btn', 'btn-default', 'pull-left'] %>
    <%= content_tag(:a, 'New Course',
      class: ['btn', 'btn-primary', 'pull-right'],
      type: 'text',
      href: new_course_path
    ) %>
  </div>
</section>

app/views/courses/new.html.erb
<section class="courses-new-container">
  <div class="jumbotron">
    <div class="container">
      <h1>New course</h1>
    </div>
  </div>

  <div class="container">
    <%= render 'form' %>
    <%= link_to 'Back', courses_path, class: ['btn', 'btn-default', 'pull-left'] %>
  </div>
</section>

app/views/courses/show.html.erb
<section class="courses-show-container">
  <div class="jumbotron">
    <div class="container">
      <h1>Course</h1>
    </div>
  </div>

  <div class="container">
    <% if notice %>
      <div class="alert alert-success" role="alert">
        <span class="sr-only">Success:</span>
        <%= notice %>
      </div>
    <% end %>

    <table class="table table-responsive">
      <tbody>
        <tr>
          <td><b>#</b></td>
          <td><%= @course.id %></td>
        </tr>

        <tr>
          <td><b>Name</b></td>
          <td><%= @course.name %></td>
        </tr>

        <tr>
          <td><b>Description</b></td>
          <td><%= @course.description %></td>
        </tr>

        <tr>
          <td><b>Status</b></td>
          <td><%= @course.status %></td>
        </tr>
      </tbody>
    </table>

    <%= link_to 'Back', courses_path, class: ['btn', 'btn-default', 'pull-left'] %>
    <%= link_to 'Home', root_path(), class: ['btn', 'btn-primary', 'pull-right'] %>
    <%= link_to 'Edit', edit_course_path(@course), class: ['btn', 'btn-default', 'pull-right'] %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProficiencyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= simple_form_for @student, :html => {:role => 'form', :"data-toggle" => 'validator'} do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= label_tag(:name, "Name") %>
    <%= f.text_field :name,
      class: ['form-control'],
      id: 'name',
      required: 'required',
      pattern: "^[a-zA-Z\u00C0-\u00FF\s]+$",
      maxlength: '45',
      autofocus: 'autofocus'
    %>
    <span class="help-block with-errors"></span>
  </div>

  <div class="form-group">
    <%= label_tag(:register_number, "Register Number") %>
    <%= f.text_field :register_number,
      class: ['form-control'],
      id: 'register_number',
      :required => 'required',
      maxlength: '45'
    %>
    <span class="help-block with-errors"></span>
  </div>

  <div class="form-group">
    <%= label_tag(:status, "Status") %>
    <%= f.number_field :status,
      class: ['form-control'],
      id: 'status',
      pattern: "^[0-9]+$",
      :required => 'required',
      min: '0'
    %>
    <span class="help-block with-errors"></span>
  </div>
  <%= f.button :submit, class: ['btn-primary', 'pull-right'] %>
<% end %>

app/views/students/edit.html.erb
<section class="students-edit-container">
  <div class="jumbotron">
    <div class="container">
      <h1>Editing student</h1>
    </div>
  </div>

  <div class="container">
    <%= render 'form' %>
    <%= link_to 'Back', students_path, class: ['btn', 'btn-default', 'pull-left'] %>
    <%= link_to 'Show', @student, class: ['btn', 'btn-default', 'pull-left'] %>
  </div>
</section>

app/views/students/index.html.erb
<section class="students-index-container"
  ng-controller="StudentsIndexController as studentsIndexController">
  <div class="jumbotron">
    <div class="container">
      <h1>Listing students</h1>
    </div>
  </div>

  <div class="container">
    <table class="table table-responsive">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Register Number</th>
          <th>Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @students.each do |student| %>
          <tr>
            <td><%= student.id %></td>
            <td><%= student.name %></td>
            <td><%= student.register_number %></td>
            <td><%= student.status %></td>
            <td><%= link_to 'Show', student %></td>
            <td><%= link_to 'Edit', edit_student_path(student) %></td>
            <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Back', root_path, class: ['btn', 'btn-default', 'pull-left'] %>
    <%= content_tag(:a, 'New Student',
      class: ['btn', 'btn-primary', 'pull-right'],
      type: 'text',
      href: new_student_path
    ) %>
  </div>
</section>

app/views/students/new.html.erb
<section class="students-new-container">
  <div class="jumbotron">
    <div class="container">
      <h1>New student</h1>
    </div>
  </div>

  <div class="container">
    <%= render 'form' %>
    <%= link_to 'Back', students_path, class: ['btn', 'btn-default', 'pull-left'] %>
  </div>
</section>

app/views/students/show.html.erb
<section class="students-show-container">
  <div class="jumbotron">
    <div class="container">
      <h1>Student</h1>
    </div>
  </div>

  <div class="container">
    <% if notice %>
      <div class="alert alert-success" role="alert">
        <span class="sr-only">Success:</span>
        <%= notice %>
      </div>
    <% end %>

    <table class="table table-responsive">
      <tbody>
        <tr>
          <td><b>#</b></td>
          <td><%= @student.id %></td>
        </tr>

        <tr>
          <td><b>Name</b></td>
          <td><%= @student.name %></td>
        </tr>

        <tr>
          <td><b>Register Number</b></td>
          <td><%= @student.register_number %></td>
        </tr>

        <tr>
          <td><b>Status</b></td>
          <td><%= @student.status %></td>
        </tr>
      </tbody>
    </table>

    <%= link_to 'Back', students_path, class: ['btn', 'btn-default', 'pull-left'] %>
    <%= link_to 'Home', root_path(), class: ['btn', 'btn-primary', 'pull-right'] %>
    <%= link_to 'Edit', edit_student_path(@student), class: ['btn', 'btn-default', 'pull-right'] %>
  </div>
</section>